project:
  type: website
  output-dir: docs

website:
  title: "Victoria Farkas"
  site-url: https://farkasvic.github.io
  repo-url: https://github.com/farkasvic/farkasvic.github.io
  navbar:
    background: light
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: projects.qmd
        text: Projects
      - href: beyond-data.qmd
        text: Beyond Data
    right:
      - href: https://linkedin.com/in/victoria-farkas-617262262
        text: LinkedIn
      - href: mailto:victoriafarkas9@gmail.com
        text: Email

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    page-layout: full
    mainfont: "Poppins"
    include-in-header: includes/dark-mode-head.html
    include-after-body: includes/dark-mode.html
